### ISSUE TITLE
Delete Appointment

### ISSUE THREAD

**Issue by jnmorse** [quiko/appointmentFront#9]
```jsx
<Button
  onPress={this.deleteAppointment(appointment._id)}
  title="D"
>
  D
</Button>
```
Should be changed to this

```jsx
<Button
  onPress={() => this.deleteAppointment(appointment._id)}
  title="D"
>
  D
</Button>
```

Specify want to use an arrow function here so that the function is not called till the button is clicked.

Also in your reducer, you had

```js
const filteredAppointment = list.filter(eachAppointment => {                
  eachAppointment._id !== action.deleted;
});
```

You want action.payload here since that contains the id.

**Comment by quiko** [comment]
yep right, it fixed the problem.
Thank you
